version: '3'
services:
  my-mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: hogerootpassword
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - /tmp/docker/tmpdata:/tmp/tmpdata
